storeproject/storeapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.loginn,name='login'),
    path('logout',views.logout,name='logout'),
    path('main',views.logged,name='main'),
    path('order/add/', views.create_view, name='add'),
    path('order/<int:pk>/', views.update_view, name='change'),
    path('order/ajax/load-courses/', views.load_courses, name='ajax_load_courses'),  # AJAX
]

storeproject/storeproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

storeproject/storeapp/models.py
from django.db import models
from django.shortcuts import render


# Create your models here.
class Purpose(models.Model):
    name=models.CharField(max_length=250)
    def __str__(self):
        return self.name


class Department(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Course(models.Model):
    department=models.ForeignKey(Department,on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Ordering(models.Model):

    name=models.CharField(max_length=250)
    birthdate=models.DateField(null=True)
    gender=models.CharField(max_length=100,null=True)
    age=models.PositiveIntegerField(null=True)
    phone_number=models.CharField(max_length=11,null=True)
    email=models.EmailField(max_length=200)
    address=models.CharField(max_length=250)
    department=models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)
    course=models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
    purpose=models.ForeignKey(Purpose,on_delete=models.SET_NULL,null=True)
    materials_provide=models.CharField(max_length=200,null=True)


    def __str__(self):
        return self.name

storeproject/storeapp/forms.py
from django import forms

from storeapp.models import Ordering, Course

Gender_choices=[
    ('Male','Male'),
    ('Female','Female'),
    ('Others','Others')
]

Materials_choices=[
    ('Note book','Note book'),
    ('Pen','Pen'),
    ('Lab products','Lab products'),
    ('Question paper','Question paper'),
    ('Guide book','Guide Book'),
    ('Test book','Test book')
]

class OrderingCreationForm(forms.ModelForm):
    gender=forms.ChoiceField(choices=Gender_choices,widget=forms.RadioSelect)
    materials_provide=forms.MultipleChoiceField(label='Materials',choices=Materials_choices,widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Ordering
        fields = ['name','birthdate','gender','age','phone_number','address','email','department',
                  'course','purpose','materials_provide'
        ]

        labels = {
                'name':'Name',
                'birthdate':'Date of Birth',
                'phone_number':'Mobile No',
                'email':'Email ID',
                'materials_provide':'Materials Provide',
        }
        widgets = {
                 'name':forms.TextInput(attrs={'class':'form-control'}),
                 'birthdate':forms.DateInput(attrs={'class':'form-control','id':'datepicker'}),
                 'phone_number':forms.NumberInput(attrs={'class':'form-control',}),
                 'address':forms.Textarea(attrs={'class':'form-control'}),
                 'email':forms.EmailInput(attrs={'class':'form-control'})

        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

storeproject/storeapp/views.py
from django.contrib import messages, auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.shortcuts import render, redirect, get_object_or_404
from .forms import  OrderingCreationForm
from .models import Ordering, Course



# Create your views here.

def index(request):
    return render(request,'index.html')

def loginn(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']

        user=authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('main')
        else:
            messages.info(request, "username or password are incorrect")
            return redirect('login')
    return render(request,'login.html')

def signup(request):
    if request.method == 'POST':
        username=request.POST['username']
        email=request.POST['email_id']
        password=request.POST['password']
        cpaswd=request.POST['cpassword']

        if password==cpaswd:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username Already Taken")
                return redirect('signup')

            elif User.objects.filter(email=email).exists():
                messages.info(request, "Email Already Taken")
                return redirect('signup')

            else:
                user=User.objects.create_user(username=username,password=password,email=email)
                user.save()
                return redirect('login')
            print("user created")

        else:
            messages.info(request,"password not matching")
            return redirect('signup')
        return redirect('/')
    return render(request,'register.html')

def logged(request):
     return render(request,"main.html")
def logout(request):
    auth.logout(request)
    return redirect('/')


def create_view(request):
    form = OrderingCreationForm()
    if request.method == 'POST':
        form = OrderingCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Order Confirmed')
            return redirect('add')
    return render(request, 'order.html', {'form': form})


def update_view(request, pk):
    ordering = get_object_or_404(Ordering, pk=pk)
    form = OrderingCreationForm(instance=ordering)
    if request.method == 'POST':
        form = OrderingCreationForm(request.POST, instance=ordering)
        if form.is_valid():
            form.save()
            return redirect('add', pk=pk)
    return render(request, 'order.html', {'form': form})


# AJAX
def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'course_dropdown_list_options.html', {'courses': courses})

storeproject/templates/course_dropdown_list_options.html
<option value="">----------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

storeproject/templates/footer.html
<div class="footer  navbar-fixed-bottom my-footer">
    <p class="text-center">&copy; CS TECH PVT LMT.All rights Reserved</p>
</div>

storeproject/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >

    <title>Home</title>

</head>
<body>



<div class="super_container" >

{% include 'navbar.html' %}



{% block content %}
    <div class="about">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="section_title"><h1>WELCOME TO THE STORE</h1></div>
				</div>

			</div>
			<div class="row about_row">
					<div class="about_content">
						<div class="text_highlight">Here students can buy school accessories.</div>
						<div class="about_text">
							<p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet .Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu laoreet ante, sollicitudin volutpat quam. Vestibulum posuere malesuada ultrices. In pulvinar rhoncus lacus at aliquet. Nunc vitae lacus varius, auctor nisi sit amet, consectetur mauris. Curabitur sodales semper est, vel faucibus urna laoreet vel. Ut justo diam, sodales non pulvinar at, vulputate quis neque. Etiam aliquam purus vel ultricies consequat.</p>

						</div>
						<div class="button about_button"><a href="#">read more</a></div>
					</div>
				</div>

			</div>

		</div>

	</div>


{% endblock %}
{% include 'footer.html' %}
</div>

<script src="{% static 'js/slim.min.js' %}"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

storeproject/templates/login.html
<!DOCTYPE html>
<!-- Coding by CodingLab | www.codinglabweb.com-->
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

      <style>
                                       @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #4070f4;
}
.wrapper{
  position: relative;
  max-width: 430px;
  width: 100%;
  background: #fff;
  padding: 34px;
  border-radius: 6px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.2);
}
.wrapper h2{
  position: relative;
  font-size: 22px;
  font-weight: 600;
  color: #333;
}
.wrapper h2::before{
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 28px;
  border-radius: 12px;

}
.wrapper form{
  margin-top: 30px;
}
.wrapper form .input-box{
  height: 52px;
  margin: 18px 0;
}
form .input-box input{
  height: 100%;
  width: 100%;
  outline: none;
  padding: 0 15px;
  font-size: 17px;
  font-weight: 400;
  color: #333;
  border: 1.5px solid #C7BEBE;
  border-bottom-width: 2.5px;
  border-radius: 6px;
  transition: all 0.3s ease;
}
.input-box input:focus,
.input-box input:valid{
  border-color: #4070f4;
}
form .policy{
  display: flex;
  align-items: center;
}
form h3{
  color: #707070;
  font-size: 14px;
  font-weight: 500;
  margin-left: 10px;
}
.input-box.button input{
  color: #fff;
  letter-spacing: 1px;
  border: none;
  background: #4070f4;
  cursor: pointer;
}
.input-box.button input:hover{
  background: #0e4bf1;
}
form .text h3{
 color: #333;
 width: 100%;
 text-align: center;
}
form .text h3 a{
  color: #4070f4;
  text-decoration: none;
}
form .text h3 a:hover{
  text-decoration: underline;
}
h5{
   color: red;
   text-align: center;
}
      </style>
   </head>
<body>
  <div class="wrapper">
    <h2>Sign in</h2>
    <form action="" method="post">
      {% csrf_token %}
      <div class="input-box">
        <input type="text" name="username" placeholder="Enter your username" >
      </div>

      <div class="input-box">
        <input type="password" name="password" placeholder="Create password" >
      </div>


      <div class="input-box button">
        <input type="Submit" value="Login">
      </div>
      <div class="text">
        <h3>You don't have an account? <a href="/signup">Signup now</a></h3>
      </div>
    </form>
    {% for msg in messages %}
      <h5>{{msg}}</h5>
    {% endfor %}
  </div>

</body>
</html>

storeproject/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >

    <title>Title</title>

</head>
<body>



<div class="super_container" >

<div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">COLLEGE STORE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">{{user.username}}</a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="logout">Logout</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>
</div>
{% block content %}
    <div class="about">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="section_title"><h1></h1></div>
				</div>

			</div>
			<div class="row about_row">
					<div class="about_content">
						<div class="text_highlight">click here to order.</div>
						<div>
                            <a href="order/add/" class="btn btn-primary" role="button">Order</a>
                        </div>
					</div>
            </div>

        </div>

    </div>




{% endblock %}
{% include 'footer.html' %}
</div>

<script src="{% static 'js/slim.min.js' %}"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

storeproject/templates/message.html
{% if messages %}
<div class="messages">
    {% for msg in messages %}
     {% if message.tags %} class="{{ message.tags }}" {% endif %}<h5>{{ msg }}</h5>
    {% endfor %}
    <h6><a href="/">Go Back To Home</a></h6>
</div>
{% endif %}

storeproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">COLLEGE STORE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Department
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer science</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Biology">Biology science</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electronics">Electronics</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Engineering">Engineering</a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="main">Hello {{user.username}}</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="logout">Logout</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="signup">Register</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="login">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

storeproject/templates/order.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Order</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

</head>
<body>
<div class="container">
    <div class="card">
        <div class="card-header">
            ORDER FORM
        </div>
        <div class="card-body">
            <form method="post" id="OrderingForm" data-courses-url="{% url 'ajax_load_courses' %}" class="form-horizontal" role="form">
            {% csrf_token %}
            {% include 'message.html' %}
                {{ form.as_p }}
                <input type="submit" value="Submit" class="btn btn-primary">

                <a href="/logout" class="btn btn-success" role="button">Logout</a>

            </form>

        </div>
    </div>
</div>
<script src="{% static 'js/slim.min.js' %}"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#OrderingForm").attr("data-courses-url");  // get the url of the `load_courses` view
        const departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /members/ajax/load-courses/ )
            data: {
                'department_id': departmentId       // GET parameters
            },
            success: function (data) {
                $("#id_course").html(data);
            }
        });

    });

</script>
<script>
  $( function() {
    $( "#datepicker" ).datepicker();
    $( "#anim" ).on( "change", function() {
      $( "#datepicker" ).datepicker( "option", "showAnim", $( this ).val() );
    });
  } );
  </script>
</body>
</html>

storeproject/templates/register.html
<!DOCTYPE html>
<!-- Coding by CodingLab | www.codinglabweb.com-->
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registration or Sign Up</title>

      <style>
                                       @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #4070f4;
}
.wrapper{
  position: relative;
  max-width: 430px;
  width: 100%;
  background: #fff;
  padding: 34px;
  border-radius: 6px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.2);
}
.wrapper h2{
  position: relative;
  font-size: 22px;
  font-weight: 600;
  color: #333;
}
.wrapper h2::before{
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 28px;
  border-radius: 12px;

}
.wrapper form{
  margin-top: 30px;
}
.wrapper form .input-box{
  height: 52px;
  margin: 18px 0;
}
form .input-box input{
  height: 100%;
  width: 100%;
  outline: none;
  padding: 0 15px;
  font-size: 17px;
  font-weight: 400;
  color: #333;
  border: 1.5px solid #C7BEBE;
  border-bottom-width: 2.5px;
  border-radius: 6px;
  transition: all 0.3s ease;
}
.input-box input:focus,
.input-box input:valid{
  border-color: #4070f4;
}
form .policy{
  display: flex;
  align-items: center;
}
form h3{
  color: #707070;
  font-size: 14px;
  font-weight: 500;
  margin-left: 10px;
}
.input-box.button input{
  color: #fff;
  letter-spacing: 1px;
  border: none;
  background: #4070f4;
  cursor: pointer;
}
.input-box.button input:hover{
  background: #0e4bf1;
}
form .text h3{
 color: #333;
 width: 100%;
 text-align: center;
}
form .text h3 a{
  color: #4070f4;
  text-decoration: none;
}
form .text h3 a:hover{
  text-decoration: underline;
}
h5{
   color: red;
   text-align: center;
}
      </style>
   </head>
<body>
  <div class="wrapper">
    <h2>SIGN UP</h2>
    <form action="" method="post">
      {% csrf_token %}
      <div class="input-box">
        <input type="text" name="username" placeholder="Enter your username" >
      </div>
      <div class="input-box">
        <input type="text" name="email_id" placeholder="Enter your email">
      </div>
      <div class="input-box">
        <input type="password" name="password" placeholder="Create password" >
      </div>
      <div class="input-box">
        <input type="password" name="cpassword" placeholder="Confirm password" >
      </div>

      <div class="input-box button">
        <input type="Submit" value="Register">
      </div>
      <div class="text">
        <h3>Already have an account? <a href="/login">Signin now</a></h3>
      </div>
    </form>
    {% for msg in messages %}
      <h5>{{msg}}</h5>
    {% endfor %}
  </div>

</body>
</html>